'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OpenShell32.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_EXlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_EXlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_EXlow_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_EXlow_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_full_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_full_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_good_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_good_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_low_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_low_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_mid_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_mid_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bat_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bat_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_EXlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_EXlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_EXlow_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_EXlow_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_full_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_full_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_good() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_good", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_good_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_good_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_low_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_low_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_mid_charge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_mid_charge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BigBat_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BigBat_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CreditsEgg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CreditsEgg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CreditsEgg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CreditsEgg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9642E56436CEDDF50C2BE319FC01B769336B17C239679F181CA95B8D3B33DE9D6213E8997445DCEAB028C372F6F37B042E457A0BA3AE8ECA66187161DC603CBB.
        '''</summary>
        Friend ReadOnly Property PrivateIntegKey() As String
            Get
                Return ResourceManager.GetString("PrivateIntegKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;persistedQuery version=&quot;1.0&quot;&gt;&lt;viewInfo iconSize=&quot;32&quot; stackIconSize=&quot;0&quot; displayName=&quot;Search Result&quot; autoListFlags=&quot;0&quot;&gt;&lt;visibleColumns&gt;&lt;column viewField=&quot;System.ItemNameDisplay&quot;/&gt;&lt;column viewField=&quot;System.DateModified&quot;/&gt;&lt;column viewField=&quot;System.ItemTypeText&quot;/&gt;&lt;column viewField=&quot;System.Size&quot;/&gt;&lt;column viewField=&quot;System.ItemFolderPathDisplayNarrow&quot;/&gt;&lt;/visibleColumns&gt;&lt;sortList&gt;&lt;sort viewField=&quot;System.Search.Rank&quot; direction=&quot;descending&quot;/&gt;&lt;sort viewField=&quot;System.DateModified&quot; direction=&quot;desc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SearchDoc() As String
            Get
                Return ResourceManager.GetString("SearchDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.8.8.
        '''</summary>
        Friend ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
